# Generated by Django 2.2 on 2019-04-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20190408_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerinvite',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamrequest',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
