# Generated by Django 2.2 on 2019-04-05 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_landlord_player_sponsor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='data_of_birth',
            new_name='date_of_birth',
        ),
    ]
