# Generated by Django 2.2 on 2019-04-07 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorships', '0002_delete_sponsor'),
        ('core', '0004_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='packge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sponsorships.SponsorshipPackge'),
        ),
    ]
