# Generated by Django 2.2 on 2019-04-04 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorshipPackge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('Type', models.CharField(blank=True, choices=[('golden', 'GOLDEN'), ('silver', 'SILVER')], max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(blank=True, max_length=1024, null=True)),
                ('commercial_register_number', models.CharField(blank=True, max_length=2048, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('package', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sponsorships.SponsorshipPackge')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
