# Generated by Django 2.2 on 2019-04-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorships', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sponsor',
        ),
    ]
