# Generated by Django 2.2 on 2019-04-07 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_auto_20190407_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='standings',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.Match'),
        ),
    ]
