# Generated by Django 2.2 on 2019-04-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_standings_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='participateinvite',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
