# Generated by Django 2.2 on 2019-04-07 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_playerinvite_teamrequest'),
        ('leagues', '0005_participateinvite_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='participateinvite',
            name='team',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='teams.Team'),
            preserve_default=False,
        ),
    ]
