# Generated by Django 2.2 on 2019-04-07 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0007_league_fees_per_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participateinvite',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.Team'),
        ),
    ]
