# Generated by Django 2.2 on 2019-04-10 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_auto_20190408_1615'),
        ('leagues', '0009_participateinvite_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='winner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='league_winner', to='teams.Team'),
        ),
    ]
