# Generated by Django 2.2 on 2019-04-10 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0010_league_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standings',
            name='match',
        ),
    ]
