# Generated by Django 2.2 on 2019-04-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0011_remove_standings_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
